name: Vietnamese_and_Flutter_Educamp
description: An educational app showcasing various Flutter mini-app with the theme of introducing
  the beautiful Vietnamese language

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.0
  audioplayers: ^0.16.1
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  provider: ^4.3.2+2
  timeago: ^2.0.27
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ep1_image/
    - assets/ep2_card/
    - assets/ep3_random/
    - assets/ep4_audio/
    - assets/ep5_data_structure/
    - assets/ep6_custom_components/

  fonts:
    - family: Fira Sans Extra Condensed
      fonts:
        - asset: assets/FiraSansExtraCondensed-Medium.ttf
    - family: Sources Sans Pro
      fonts:
          - asset: assets/SourceSansPro-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
